// [AI-GENERATED] This file was entirely generated by AI
import * as vscode from 'vscode';
import * as net from 'net';
import * as http from 'http';

let server: net.Server | null = null;
let notificationServer: http.Server | null = null;
let statusBarItem: vscode.StatusBarItem;

// SSE 订阅者管理
interface SSESubscriber {
    res: http.ServerResponse;
    sessionId: string;
}
let sseSubscribers: SSESubscriber[] = [];

// 调试会话状态
interface DebugSessionState {
    isPaused: boolean;
    lastPausedLocation: any;
    breakpointHitCount: number;
}
// 记录 AI（bridge）设置的断点，用于区分手动断点
const bridgeBreakpoints: Set<string> = new Set();
const bpKey = (fp: string, ln: number) => `${fp}:${ln}`;

let debugSessionState: DebugSessionState = {
    isPaused: false,
    lastPausedLocation: null,
    breakpointHitCount: 0
};

// 请求处理器
interface Request {
    command: string;
    params: Record<string, any>;
}

interface Response {
    success: boolean;
    [key: string]: any;
}

export function activate(context: vscode.ExtensionContext) {
    console.log('[VSDebug Bridge] 扩展已激活');

    // 创建状态栏项
    statusBarItem = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Right, 100);
    statusBarItem.command = 'vsdbg-bridge.status';
    context.subscriptions.push(statusBarItem);

    // 注册命令
    context.subscriptions.push(
        vscode.commands.registerCommand('vsdbg-bridge.start', startServer),
        vscode.commands.registerCommand('vsdbg-bridge.stop', stopServer),
        vscode.commands.registerCommand('vsdbg-bridge.status', showStatus)
    );

    // 监听断点触发事件 - 核心功能
    context.subscriptions.push(
        vscode.debug.onDidChangeActiveStackItem(async (stackItem) => {
            if (stackItem && 'frameId' in stackItem) {
                // 断点触发（有具体栈帧）！
                debugSessionState.isPaused = true;
                debugSessionState.breakpointHitCount++;
                
                // 获取当前位置信息
                const locationResponse = await getCurrentLocation();
                debugSessionState.lastPausedLocation = locationResponse;
                
                // 提取内层 location 对象（包含 filePath/line/column）
                const location = locationResponse.location || locationResponse;
                
                console.log('[VSDebug Bridge] 断点触发:', location);
                
                // 通知所有 SSE 订阅者
                broadcastSSE({
                    type: 'breakpointHit',
                    timestamp: Date.now(),
                    hitCount: debugSessionState.breakpointHitCount,
                    location: location
                });
            } else if (stackItem && 'threadId' in stackItem) {
                // 用户在线程视图选择了某线程（未展开到栈帧），仍然暂停
                debugSessionState.isPaused = true;
            } else {
                // stackItem 为 null/undefined → 程序真正恢复运行了
                if (debugSessionState.isPaused) {
                    debugSessionState.isPaused = false;
                    broadcastSSE({
                        type: 'resumed',
                        timestamp: Date.now()
                    });
                }
            }
        })
    );

    // 监听调试会话结束
    context.subscriptions.push(
        vscode.debug.onDidTerminateDebugSession((session) => {
            debugSessionState.isPaused = false;
            debugSessionState.lastPausedLocation = null;
            broadcastSSE({
                type: 'sessionEnded',
                timestamp: Date.now(),
                sessionName: session.name
            });
        })
    );

    // 自动启动
    const config = vscode.workspace.getConfiguration('vsdbg-bridge');
    if (config.get<boolean>('autoStart', true)) {
        startServer();
        startNotificationServer(); // 同时启动通知服务器
    }
}

export function deactivate() {
    stopServer();
    stopNotificationServer();
}

function startServer() {
    if (server) {
        vscode.window.showInformationMessage('调试桥接服务器已在运行');
        return;
    }

    const config = vscode.workspace.getConfiguration('vsdbg-bridge');
    const port = config.get<number>('port', 19530);

    server = net.createServer((socket) => {
        console.log('[VSDebug Bridge] 新连接');

        let buffer = Buffer.alloc(0);

        socket.on('data', async (data) => {
            buffer = Buffer.concat([buffer, data]);

            // 处理可能的多个请求
            while (buffer.length >= 8) {
                const lengthStr = buffer.slice(0, 8).toString('utf-8');
                const length = parseInt(lengthStr, 10);

                if (isNaN(length) || buffer.length < 8 + length) {
                    break;
                }

                const requestData = buffer.slice(8, 8 + length).toString('utf-8');
                buffer = buffer.slice(8 + length);

                try {
                    const request: Request = JSON.parse(requestData);
                    const response = await handleCommand(request.command, request.params || {});
                    sendResponse(socket, response);
                } catch (err) {
                    sendResponse(socket, { success: false, error: String(err) });
                }
            }
        });

        socket.on('error', (err) => {
            console.log('[VSDebug Bridge] Socket错误:', err.message);
        });

        socket.on('close', () => {
            console.log('[VSDebug Bridge] 连接关闭');
        });
    });

    server.listen(port, '127.0.0.1', () => {
        console.log(`[VSDebug Bridge] 服务器启动在端口 ${port}`);
        vscode.window.showInformationMessage(`调试桥接服务器已启动 (端口: ${port})`);
        updateStatusBar(true, port);
    });

    server.on('error', (err) => {
        console.error('[VSDebug Bridge] 服务器错误:', err);
        vscode.window.showErrorMessage(`调试桥接服务器启动失败: ${err.message}`);
        server = null;
        updateStatusBar(false);
    });
}

function stopServer() {
    if (server) {
        server.close();
        server = null;
        vscode.window.showInformationMessage('调试桥接服务器已停止');
        updateStatusBar(false);
    }
}

// ========== SSE 通知服务器 ==========

function startNotificationServer() {
    if (notificationServer) {
        console.log('[VSDebug Bridge] 通知服务器已在运行');
        return;
    }

    const config = vscode.workspace.getConfiguration('vsdbg-bridge');
    const notificationPort = config.get<number>('notificationPort', 19531);

    notificationServer = http.createServer((req, res) => {
        // CORS 头
        res.setHeader('Access-Control-Allow-Origin', '*');
        res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
        res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

        if (req.method === 'OPTIONS') {
            res.writeHead(200);
            res.end();
            return;
        }

        const url = req.url || '/';

        if (url === '/events' || url.startsWith('/events?')) {
            // SSE 端点
            res.writeHead(200, {
                'Content-Type': 'text/event-stream',
                'Cache-Control': 'no-cache',
                'Connection': 'keep-alive'
            });

            // 生成会话 ID
            const sessionId = `session_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
            
            // 添加到订阅者列表
            const subscriber: SSESubscriber = { res, sessionId };
            sseSubscribers.push(subscriber);
            console.log(`[VSDebug Bridge] SSE 订阅者连接: ${sessionId}, 当前订阅者数: ${sseSubscribers.length}`);

            // 发送初始连接确认
            res.write(`data: ${JSON.stringify({
                type: 'connected',
                sessionId: sessionId,
                timestamp: Date.now(),
                debugState: {
                    isPaused: debugSessionState.isPaused,
                    breakpointHitCount: debugSessionState.breakpointHitCount,
                    lastLocation: debugSessionState.lastPausedLocation
                }
            })}\n\n`);

            // 心跳保持连接
            const heartbeat = setInterval(() => {
                if (!res.writableEnded) {
                    res.write(`: heartbeat\n\n`);
                }
            }, 30000);

            // 断开连接时清理
            req.on('close', () => {
                clearInterval(heartbeat);
                sseSubscribers = sseSubscribers.filter(s => s.sessionId !== sessionId);
                console.log(`[VSDebug Bridge] SSE 订阅者断开: ${sessionId}, 当前订阅者数: ${sseSubscribers.length}`);
            });

        } else if (url === '/status') {
            // 状态查询端点
            res.writeHead(200, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({
                success: true,
                subscriberCount: sseSubscribers.length,
                debugState: debugSessionState
            }));

        } else {
            res.writeHead(404, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({ error: 'Not found' }));
        }
    });

    notificationServer.listen(notificationPort, '127.0.0.1', () => {
        console.log(`[VSDebug Bridge] 通知服务器启动在端口 ${notificationPort}`);
    });

    notificationServer.on('error', (err) => {
        console.error('[VSDebug Bridge] 通知服务器错误:', err);
        notificationServer = null;
    });
}

function stopNotificationServer() {
    if (notificationServer) {
        // 通知所有订阅者服务器关闭
        broadcastSSE({ type: 'serverClosing', timestamp: Date.now() });
        
        // 关闭所有连接
        sseSubscribers.forEach(s => {
            if (!s.res.writableEnded) {
                s.res.end();
            }
        });
        sseSubscribers = [];

        notificationServer.close();
        notificationServer = null;
        console.log('[VSDebug Bridge] 通知服务器已停止');
    }
}

function broadcastSSE(data: any) {
    const message = `data: ${JSON.stringify(data)}\n\n`;
    sseSubscribers.forEach(subscriber => {
        if (!subscriber.res.writableEnded) {
            subscriber.res.write(message);
        }
    });
}

function showStatus() {
    if (server) {
        const config = vscode.workspace.getConfiguration('vsdbg-bridge');
        const port = config.get<number>('port', 19530);
        vscode.window.showInformationMessage(`调试桥接服务器运行中 (端口: ${port})`);
    } else {
        vscode.window.showInformationMessage('调试桥接服务器未运行');
    }
}

function updateStatusBar(running: boolean, port?: number) {
    if (running) {
        statusBarItem.text = `$(debug) Bridge: ${port}`;
        statusBarItem.tooltip = '调试桥接服务器运行中，点击查看状态';
        statusBarItem.backgroundColor = undefined;
    } else {
        statusBarItem.text = '$(debug-disconnect) Bridge: 已停止';
        statusBarItem.tooltip = '调试桥接服务器已停止';
    }
    statusBarItem.show();
}

function sendResponse(socket: net.Socket, response: Response) {
    const data = JSON.stringify(response);
    const buffer = Buffer.from(data, 'utf-8');
    const header = buffer.length.toString().padStart(8, '0');
    socket.write(header + data);
}

// 带超时的 Promise 包装
function withTimeout<T>(promise: Promise<T>, timeoutMs: number, errorMsg: string): Promise<T> {
    return new Promise((resolve, reject) => {
        const timer = setTimeout(() => {
            reject(new Error(errorMsg));
        }, timeoutMs);

        promise
            .then((result) => {
                clearTimeout(timer);
                resolve(result);
            })
            .catch((err) => {
                clearTimeout(timer);
                reject(err);
            });
    });
}

// 安全的 customRequest 包装，不会影响调试会话
async function safeCustomRequest(session: vscode.DebugSession, command: string, args?: any, timeoutMs: number = 3000): Promise<any> {
    try {
        // 将 Thenable 转换为 Promise
        const promise = Promise.resolve(session.customRequest(command, args));
        return await withTimeout(
            promise,
            timeoutMs,
            `请求 ${command} 超时`
        );
    } catch (err) {
        throw err;
    }
}

// 命令处理
async function handleCommand(command: string, params: Record<string, any>): Promise<Response> {
    console.log(`[VSDebug Bridge] 处理命令: ${command}`, params);

    switch (command) {
        case 'getBreakpoints':
            return getBreakpoints();
        case 'getCurrentLocation':
            return getCurrentLocation();
        case 'getVariables':
            return getVariables(params.scope || 'all');
        case 'getCallStack':
            return getCallStack();
        case 'continue':
            return debugControl('continue');
        case 'stepOver':
            return debugControl('stepOver');
        case 'stepInto':
            return debugControl('stepInto');
        case 'stepOut':
            return debugControl('stepOut');
        case 'pause':
            return debugControl('pause');
        case 'restart':
            return debugControl('restart');
        case 'stop':
            return debugControl('stop');
        case 'evaluate':
            return evaluateExpression(params.expression || '');
        case 'setBreakpoint':
            return setBreakpoint(params.filePath, params.line, params.condition);
        case 'removeBreakpoint':
            return removeBreakpoint(params.filePath, params.line, params.includeManual);
        case 'removeAllBreakpoints':
            return removeAllBreakpoints(params.includeManual);
        default:
            return { success: false, error: `未知命令: ${command}` };
    }
}

// 获取所有断点
function getBreakpoints(): Response {
    const breakpoints = vscode.debug.breakpoints;
    const result: any[] = [];

    for (const bp of breakpoints) {
        if (bp instanceof vscode.SourceBreakpoint) {
            result.push({
                filePath: bp.location.uri.fsPath,
                line: bp.location.range.start.line + 1, // VSCode行号从0开始
                enabled: bp.enabled,
                condition: bp.condition || null,
                hitCondition: bp.hitCondition || null,
                logMessage: bp.logMessage || null
            });
        }
    }

    return { success: true, breakpoints: result };
}

// 获取当前调试位置 - 使用 activeStackItem API 获取真实的调试暂停位置
async function getCurrentLocation(): Promise<Response> {
    const session = vscode.debug.activeDebugSession;
    if (!session) {
        return { success: false, error: '没有活跃的调试会话', paused: false };
    }

    // 使用 activeStackItem API 获取当前栈帧
    const activeStackItem = vscode.debug.activeStackItem;
    if (activeStackItem && 'frameId' in activeStackItem) {
        const stackFrame = activeStackItem as any;
        try {
            // 使用 frameId 和 threadId 获取栈帧详细信息
            const stackResponse = await safeCustomRequest(session, 'stackTrace', { 
                threadId: stackFrame.threadId, 
                startFrame: 0,
                levels: 1 
            }, 2000);
            
            if (stackResponse.stackFrames && stackResponse.stackFrames.length > 0) {
                const frame = stackResponse.stackFrames[0];
                return {
                    success: true,
                    location: {
                        filePath: frame.source?.path || 'unknown',
                        line: frame.line || 0,
                        column: frame.column || 0
                    },
                    sessionName: session.name,
                    sessionType: session.type,
                    paused: true
                };
            }
        } catch (err) {
            return { 
                success: false, 
                error: `获取栈帧信息失败: ${err}`,
                sessionName: session.name,
                sessionType: session.type,
                paused: true
            };
        }
    }

    // activeStackItem 存在但没有 frameId（如线程级选择）或为 undefined
    // 尝试直接通过 DAP 获取栈帧
    try {
        // 先获取线程
        const threadResponse = await safeCustomRequest(session, 'threads', {}, 2000);
        if (threadResponse.threads && threadResponse.threads.length > 0) {
            // 取第一个暂停的线程
            const threadId = threadResponse.threads[0].id;
            const stackResponse = await safeCustomRequest(session, 'stackTrace', { 
                threadId, 
                startFrame: 0,
                levels: 1 
            }, 2000);
            
            if (stackResponse.stackFrames && stackResponse.stackFrames.length > 0) {
                const frame = stackResponse.stackFrames[0];
                return {
                    success: true,
                    location: {
                        filePath: frame.source?.path || 'unknown',
                        line: frame.line || 0,
                        column: frame.column || 0
                    },
                    sessionName: session.name,
                    sessionType: session.type,
                    paused: true
                };
            }
        }
    } catch (err) {
        // fallback 失败，说明程序可能正在运行
    }

    return { 
        success: true, 
        sessionName: session.name, 
        sessionType: session.type, 
        paused: false,
        error: '没有活跃的栈帧，程序可能正在运行'
    };
}

// 获取变量 - 使用 activeStackItem API 避免直接发送 DAP 请求
async function getVariables(scope: string): Promise<Response> {
    const session = vscode.debug.activeDebugSession;
    if (!session) {
        return { success: false, error: '没有活跃的调试会话' };
    }

    try {
        // 尝试使用 activeStackItem API (VSCode 1.67+)
        const activeStackItem = vscode.debug.activeStackItem;
        if (!activeStackItem) {
            return { success: false, error: '没有活跃的栈帧，程序可能正在运行' };
        }

        // 检查是否是 DebugStackFrame 类型
        if (!('frameId' in activeStackItem)) {
            return { success: false, error: '当前栈帧类型不支持获取变量' };
        }

        const frameId = (activeStackItem as any).frameId;
        if (!frameId) {
            return { success: false, error: '无法获取栈帧ID' };
        }

        // 获取作用域（使用超时保护）
        const scopesResponse = await safeCustomRequest(session, 'scopes', { frameId }, 2000);
        const variables: Record<string, any> = {};

        // 只获取 local 作用域，避免获取 global 导致超时
        const scopesToFetch = scope === 'global' 
            ? scopesResponse.scopes.filter((s: any) => s.name.toLowerCase().includes('global'))
            : scope === 'local'
            ? scopesResponse.scopes.filter((s: any) => s.name.toLowerCase().includes('local'))
            : scopesResponse.scopes.slice(0, 2); // all 时只取前两个作用域

        for (const scopeInfo of scopesToFetch) {
            try {
                const varsResponse = await safeCustomRequest(session, 'variables', {
                    variablesReference: scopeInfo.variablesReference
                }, 2000);

                // 限制变量数量，避免数据过大
                const limitedVars = varsResponse.variables.slice(0, 100).map((v: any) => ({
                    name: v.name,
                    value: String(v.value).substring(0, 500), // 增加值长度限制
                    type: v.type || 'unknown'
                }));

                variables[scopeInfo.name] = limitedVars;
            } catch (scopeErr) {
                // 单个作用域获取失败不影响其他
                variables[scopeInfo.name] = [{ name: 'error', value: String(scopeErr), type: 'error' }];
            }
        }

        return { success: true, variables };
    } catch (err) {
        return { success: false, error: String(err) };
    }
}

// 获取调用栈 - 使用 activeStackItem API 避免直接发送 DAP 请求
async function getCallStack(): Promise<Response> {
    const session = vscode.debug.activeDebugSession;
    if (!session) {
        return { success: false, error: '没有活跃的调试会话' };
    }

    const activeStackItem = vscode.debug.activeStackItem;

    // 优先从 activeStackItem 获取栈帧信息
    if (activeStackItem && 'frameId' in activeStackItem) {
        try {
            const stackFrame = activeStackItem as any;
            const frameId = stackFrame.frameId;
            const threadId = stackFrame.threadId;

            if (!frameId || !threadId) {
                return { success: false, error: '无法获取栈帧信息' };
            }

            // 先通过 scopes 请求验证栈帧是否有效
            await safeCustomRequest(session, 'scopes', { frameId }, 2000);

            const stackResponse = await safeCustomRequest(session, 'stackTrace', { 
                threadId, 
                startFrame: 0,
                levels: 50 
            }, 3000);

            const callStack = stackResponse.stackFrames.map((frame: any) => ({
                name: frame.name,
                filePath: frame.source?.path || 'unknown',
                line: frame.line,
                column: frame.column
            }));

            return { success: true, callStack };
        } catch (err) {
            return { success: false, error: String(err) };
        }
    }

    // 没有 activeStackItem 或没有 frameId（异常断点等），回退到 DAP threads
    try {
        const threadResponse = await safeCustomRequest(session, 'threads', {}, 2000);
        if (!threadResponse.threads || threadResponse.threads.length === 0) {
            return { success: false, error: '没有活跃的线程，程序可能正在运行' };
        }

        const threadId = threadResponse.threads[0].id;
        const stackResponse = await safeCustomRequest(session, 'stackTrace', { 
            threadId, 
            startFrame: 0,
            levels: 50 
        }, 3000);

        const callStack = stackResponse.stackFrames.map((frame: any) => ({
            name: frame.name,
            filePath: frame.source?.path || 'unknown',
            line: frame.line,
            column: frame.column
        }));

        return { success: true, callStack };
    } catch (err) {
        return { success: false, error: String(err) };
    }
}

// 调试控制
async function debugControl(action: string): Promise<Response> {
    const session = vscode.debug.activeDebugSession;
    if (!session) {
        return { success: false, error: '没有活跃的调试会话' };
    }

    try {
        switch (action) {
            case 'continue':
                await vscode.commands.executeCommand('workbench.action.debug.continue');
                break;
            case 'stepOver':
                await vscode.commands.executeCommand('workbench.action.debug.stepOver');
                break;
            case 'stepInto':
                await vscode.commands.executeCommand('workbench.action.debug.stepInto');
                break;
            case 'stepOut':
                await vscode.commands.executeCommand('workbench.action.debug.stepOut');
                break;
            case 'pause':
                await vscode.commands.executeCommand('workbench.action.debug.pause');
                break;
            case 'restart':
                await vscode.commands.executeCommand('workbench.action.debug.restart');
                break;
            case 'stop':
                await vscode.commands.executeCommand('workbench.action.debug.stop');
                break;
            default:
                return { success: false, error: `未知动作: ${action}` };
        }
        return { success: true, message: `已执行: ${action}` };
    } catch (err) {
        return { success: false, error: String(err) };
    }
}

// 评估表达式 - 使用 activeStackItem API 避免直接发送 DAP 请求
async function evaluateExpression(expression: string): Promise<Response> {
    if (!expression) {
        return { success: false, error: '表达式为空' };
    }

    const session = vscode.debug.activeDebugSession;
    if (!session) {
        return { success: false, error: '没有活跃的调试会话' };
    }

    try {
        // 尝试使用 activeStackItem API (VSCode 1.67+)
        const activeStackItem = vscode.debug.activeStackItem;
        if (!activeStackItem) {
            return { success: false, error: '没有活跃的栈帧，程序可能正在运行' };
        }

        // 检查是否是 DebugStackFrame 类型
        if (!('frameId' in activeStackItem)) {
            return { success: false, error: '当前栈帧类型不支持表达式评估' };
        }

        const frameId = (activeStackItem as any).frameId;
        if (!frameId) {
            return { success: false, error: '无法获取栈帧ID' };
        }
        
        // 使用 'watch' 上下文而非 'repl'，避免代码执行副作用
        const evalResponse = await safeCustomRequest(session, 'evaluate', {
            expression,
            frameId,
            context: 'watch'
        }, 3000);

        return {
            success: true,
            result: String(evalResponse.result).substring(0, 5000), // 增加结果长度限制
            type: evalResponse.type || 'unknown'
        };
    } catch (err) {
        return { success: false, error: String(err) };
    }
}

// 设置断点
async function setBreakpoint(filePath: string, line: number, condition?: string): Promise<Response> {
    if (!filePath || !line) {
        return { success: false, error: '文件路径和行号为必填项' };
    }

    try {
        const uri = vscode.Uri.file(filePath);
        const position = new vscode.Position(line - 1, 0); // VSCode行号从0开始
        const location = new vscode.Location(uri, position);
        
        const breakpoint = new vscode.SourceBreakpoint(location, true, condition);
        vscode.debug.addBreakpoints([breakpoint]);
        bridgeBreakpoints.add(bpKey(filePath, line));

        const conditionMsg = condition ? ` (条件: ${condition})` : '';
        return { success: true, message: `断点已设置: ${filePath}:${line}${conditionMsg}` };
    } catch (err) {
        return { success: false, error: String(err) };
    }
}

// 移除 AI 设置的断点（includeManual=true 时移除所有断点）
function removeAllBreakpoints(includeManual?: boolean): Response {
    let toRemove: vscode.Breakpoint[];
    let count: number;

    if (includeManual) {
        toRemove = vscode.debug.breakpoints;
        count = toRemove.length;
        bridgeBreakpoints.clear();
    } else {
        toRemove = vscode.debug.breakpoints.filter(bp => {
            if (bp instanceof vscode.SourceBreakpoint) {
                const fp = bp.location.uri.fsPath;
                const ln = bp.location.range.start.line + 1;
                return bridgeBreakpoints.has(bpKey(fp, ln));
            }
            return false;
        });
        count = bridgeBreakpoints.size;
        bridgeBreakpoints.clear();
    }

    vscode.debug.removeBreakpoints(toRemove);
    return { success: true, message: `已移除 ${includeManual ? '所有' : 'AI 设置的'} 断点 (${count}个)`, removedCount: count };
}

// 移除断点（默认只移除 AI 设置的，includeManual=true 时任意断点均可移除）
async function removeBreakpoint(filePath: string, line: number, includeManual?: boolean): Promise<Response> {
    if (!filePath || !line) {
        return { success: false, error: '文件路径和行号为必填项' };
    }

    const key = bpKey(filePath, line);
    if (!includeManual && !bridgeBreakpoints.has(key)) {
        return { success: false, error: `断点 ${filePath}:${line} 不是 AI 设置的，跳过` };
    }

    try {
        const breakpoints = vscode.debug.breakpoints.filter(bp => {
            if (bp instanceof vscode.SourceBreakpoint) {
                return bp.location.uri.fsPath === filePath && 
                       bp.location.range.start.line === line - 1;
            }
            return false;
        });

        if (breakpoints.length > 0) {
            vscode.debug.removeBreakpoints(breakpoints);
        }
        bridgeBreakpoints.delete(key);
        return { success: true, message: `断点已移除: ${filePath}:${line}` };
    } catch (err) {
        return { success: false, error: String(err) };
    }
}